### PR TITLE
Yearly copyright update for production branch

### PR DESCRIPTION
**Pull request by nwillhoft**
## Description

Yearly copyright update to include the new year.

## Use case

N/A

## Benefits

N/A

## Possible Drawbacks

N/A

## Testing

_Have you added/modified unit tests to test the changes?_

N/A

_If so, do the tests pass/fail?_

N/A.

_Have you run the entire test suite and no regression was detected?_

### CODE REVIEW

**Review by mira13 — APPROVED** [review]
Yearly copyright update

**Review by TamaraNaboulsi — COMMENTED** [review]
Hi Natalie. The following files were included in last year's copyright update but not in this one:

- src/belvuApp/belvuWindow.hpp
- src/dotterApp/dotter.cpp
- src/runconfig.sh

I just wanted to check why is that. Does it have anything to do with the fact that this change is for the production branch while the last one was for the develop branch?

**Comment by nwillhoft** [comment]
> Hi Natalie. The following files were included in last year's copyright update but not in this one:
> 
> * src/belvuApp/belvuWindow.hpp
> * src/dotterApp/dotter.cpp
> * src/runconfig.sh
> 
> I just wanted to check why is that. Does it have anything to do with the fact that this change is for the production branch while the last one was for the develop branch?

Thanks for identifying this! The EBI copyright string needs to be added to these 3 files.

**Review by TamaraNaboulsi — APPROVED** [review]
Changes look good!

**Pull request merged**
